version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: banco_api
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banco_api
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:7.0
    ports:
      - '6380:6379'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: banco_api
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banco_api
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: dummy_secret_key
      RAILS_ENV: development
      NODE_ENV: development

volumes:
  db_data: