default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>  
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %> 
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  database: <%= ENV.fetch("POSTGRES_DB", "banco_api") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "banco_api") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "banco_api") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "banco_api") %>_production